### ISSUE TITLE
Bugs in add student sequence diagram

### ISSUE THREAD

**Issue by dannn-tran** [AY2021S2-CS2103T-W10-4/tp#120]
The argument for execute should be `add` rather than `undo`
https://github.com/AY2021S2-CS2103T-W10-4/tp/blob/15c156a02d6463b9dae9bac73a8e90628f763229/docs/diagrams/AddSequenceDiagram.puml#L15

Should `AddressBookParser` creates, instead of activates, `AddCommandParser`, because the former invokes the constructor of the latter?
https://github.com/AY2021S2-CS2103T-W10-4/tp/blob/15c156a02d6463b9dae9bac73a8e90628f763229/docs/diagrams/AddSequenceDiagram.puml#L21-L22

**Comment by fairyinabottle4** [comment]
Noted on both, I'll make the changes
